### ISSUE TITLE
App is Failing to Start

### ISSUE THREAD

**Issue by bitshifter52** [neverlocateme/imagefap-dl-cli#1]
I just downloaded and tried your app and received the following messages:

./IFLoad.py -f test.file
Traceback (most recent call last):
  File "./IFLoad.py", line 7, in <module>
    import IFUser
  File "/media/robert/LSecondary/VM-Share/imagefap-dl-cli-master/IFUser.py", line 2, in <module>
    import request
  File "/media/robert/LSecondary/VM-Share/imagefap-dl-cli-master/request.py", line 5, in <module>
    import requests
ImportError: No module named requests

I'm running Ubuntu 21.10, Python 3.9.7, pip install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.25.1)

**Comment by koxt2** [comment]
> I just downloaded and tried your app and received the following messages:
> 
> ./IFLoad.py -f test.file Traceback (most recent call last): File "./IFLoad.py", line 7, in import IFUser File "/media/robert/LSecondary/VM-Share/imagefap-dl-cli-master/IFUser.py", line 2, in import request File "/media/robert/LSecondary/VM-Share/imagefap-dl-cli-master/request.py", line 5, in import requests ImportError: No module named requests
> 
> I'm running Ubuntu 21.10, Python 3.9.7, pip install requests Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.25.1)

I use openSUSE and also had this error. I installed python2-requests and it got to the next hurdle... "something broke."
